language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv run pip install pip==18.0
  - pipenv install --dev
  - pipenv install tox-travis
script:
  - pipenv run test
